return {
	["DummyHB"] = true,
	
	-- Reimu/Sanae
	["GoheiHB"] = true,
	["GoheiLast"] = true,
	["GoheiHeavy"] = true,
	
	-- Reimu
	["fsin"] = true,
	["bindghb"] = true,
	["bindairhb"] = true,
	["CounterProj"] = true,
	["busterhb"] = true,
	["concealedhb"] = true,
	
	-- Marisa
	["BroomHB"] = true,
	["BroomLast"] = true,
	["BroomHeavy"] = true,
	["Bombhb"] = true,
	["RadialHB"] = true,
	["SweepHitbox"] = true,
	["meteorichb"] = true,
	["nsparkhb"] = true,
	["ShootingStarHB"] = true,
	["WLhb"] = true,
	["mshb"] = true,
	
	-- Sanae
	["Wavehb"] = true,
	["ringhb"] = true,
	["Onbashirahb"] = true,
	["moseshb"] = true,
	["ritualhb"] = true,
	["esostarhb"] = true,
	
	-- Sakuya
	["KnifeHB"] = true,
	["KnifeLast"] = true,
	["KnifeHeavy"] = true,
	["propellinghb"] = true,
	["chainsawhb"] = true,
	["knifehb"] = true,
	["inscribedhb"] = true,
	["newscribedhb"] = true,
	["newscribedlasthb"] = true,
	
	-- Meiling/Reisen
	["FistHB"] = true,
	["FistLast"] = true,
	["FistHeavy"] = true,
	
	-- Meiling
	["Fist2HB"] = true,
	["fragranthb"] = true,
	["colorfulhb"] = true,
	["starproj"] = true,
	["RKFhb"] = true,
	["raginghb"] = true,
	["Divine Dragon Mock-up"] = true,
	["Final Vent Mock-up"] = true,
	["Colorful Rain Mock-up"] = true,
	["Star Dance Mock-up"] = true,
	
	-- Youmu
	["SwordHB"] = true,
	["SwordHB2"] = true,
	["SwordLast"] = true,
	["SwordLast2"] = true,
	["SwordHeavy"] = true,
	["m2rangehb"] = true,
	["crescenthb"] = true,
	["risehb"] = true,
	["insightfulslash"] = true,
	["intoleranthb"] = true,
	["Phosphoric Slash Mock-up"] = true,
	
	-- Mokou
	["MokouHB"] = true,
	["MokouLast"] = true,
	["MokouBreakerHB"] = true,
	["MokouBreakerLast"] = true,
	["MokouHeavy"] = true,
	["bindairhb"] = true,
	["flyingproj"] = true,
	["tornadohb"] = true,
	["huntinghb"] = true,
	["drivehb"] = true,
	["Firebird Mock-up"] = true,
	["Clear Sky Mock-up"] = true,
	["Bamboo Tube Mock-up"] = true,
	["Volcano Mock-up"] = true,
	["Resurrection Mock-up"] = true,
	
	-- Kokoro
	["KokoHB"] = true,
	["KokoHB2"] = true,
	["KokoLast"] = true,
	["KokoM2"] = true,
	["joyhb"] = true,
	["angryHB"] = true,
	["angryproj"] = true,
	["fearHB"] = true,
	["resolvehb"] = true,
	["delightedhb"] = true,
	["worriesHB"] = true,
	["Four Humors Mock-up"] = true,
	
	-- Yukari
	["FanHB"] = true,
	["FanLast"] = true,
	["YukariM2"] = true,
	["sign1hb"] = true,
	["nesthb"] = true,
	["nesthb2"] = true,
	["YukaTrain"] = true,
	["lendlegshb"] = true,
	["Antimatter Mock-up"] = true,
	
	-- Alice
	["SpearHB"] = true,
	["DollSpinHB"] = true,
	["ArrowHB"] = true,
	["PierceHB"] = true,
	["Doll Explosion Mock-up"] = true,
	
	-- Komachi
	["ScytheHB"] = true,
	["ScytheLast"] = true,
	["ScytheHeavy"] = true,
	["reapHB1"] = true,
	["reapHB2"] = true,
	["exorcismhb1"] = true,
	["exorcismhb2"] = true,
	["assimilatehb"] = true,
	["endlesshb"] = true,
	["FalseAngelHitbox"] = true,
	
	-- Okuu
	["RodHB"] = true,
	["RodHB2"] = true,
	["RodLast"] = true,
	["fusionstarhb"] = true,
	["radianthb"] = true,
	["meltinghb"] = true,
	["rockethb"] = true,
	["Rocket Dive Mock-up"] = true,
	["Hell Geyser Mock-up"] = true,
	["Melting Pummel Kick Mock-up"] = true,
	["Cannon Explosion Mock-up"] = true,
	["Subterranean Sun Mock-up"] = true,
	
	-- Rumia
	["RumiaHB"] = true,
	["RumiaLast"] = true,
	["RumiaHeavy"] = true,
	["nbhb"] = true,
	["nbhb2"] = true,
	["mlhb"] = true,
	["darksidehb"] = true,
	["groundhb"] = true,
	["Demarcation Mock-up"] = true,
	
	-- Cirno
	["CirnoHB"] = true,
	["CirnoHB3"] = true,
	["CirnoLast"] = true,
	["CirnoHeavy"] = true,
	["GsHB"] = true,
	["GsLast"] = true,
	["GsHeavy"] = true,
	["RapierHB"] = true,
	["RapierLast"] = true,
	["icelasthb"] = true,
	["iciclehb"] = true,
	["slidehb"] = true,
	["frozentechhb"] = true,
	["lancehb"] = true,
	["kickhb"] = true,
	["stridehb"] = true,
	["piercerhb"] = true,
	["frostpillarshb"] = true,
	["eleganthb"] = true,
	["Little Iceburg Mock-up"] = true,
	["Icicle Bomb Mock-up"] = true,
	
	-- Suika
	["SuikaHB"] = true,
	["SuikaLast"] = true,
	["armslamhb"] = true,
	["gatheringhb"] = true,
	["AtlasProj"] = true,
	["bindinghb"] = true,
	["stephb"] = true,
	["Spectre Dense Mock-up"] = true,
	["Atlas Mock-up"] = true,
	
	-- Tenshi
	["TenshiHB"] = true,
	["TenshiLast"] = true,
	["TenshiHeavy"] = true,
	["m2hb"] = true,
	["PerceptionHB"] = true,
	["revhb"] = true,
	["rapturehb"] = true,
	["skyhb"] = true,
	["unlettinghb"] = true,
	["unlettinghb2"] = true,
	["orbithb"] = true,
	["detonatehb"] = true,
	["World Creation Press Mock-up"] = true,
	
	-- Aya
	["AyaHB"] = true,
	["AyaLast"] = true,
	["AyaHB"] = true,
	["AyaHB"] = true,
	["domhb"] = true,
	["downbursthb"] = true,
	["guideancehb"] = true,
	["maplehb"] = true,
	["illuhb"] = true,
	["galehb"] = true,
	["gusthb"] = true,
	["Wind Splitter Mock-up"] = true,
	["Wind Sickle Mock-up"] = true,
	
	-- Reisen
	["bullethb"] = true,
	["discarderhb"] = true,
	["droppinghb"] = true,
	["illublasthb"] = true,
	["ripplehb"] = true,
	["stingerhb"] = true,
	["Disorder Eye Mock-up"] = true,
	
	-- Remilia
	["RemiHB"] = true,
	["RemiLast"] = true,
	["ceilinghb"] = true,
	["arrowhb"] = true,
	["tricksterhb"] = true,
	["miserablehb"] = true,
	["castlefirst"] = true,
	["castlehb"] = true,
	["heartbreakhb"] = true,
	
	-- Daiyousei
	["DaiHB1"] = true,
	["DaiHB2"] = true,
	["stormhb"] = true,
	["stormhb2"] = true,
	["ProjParry"] = true,

	-- Iku
	["IkuHB"] = true,
	["IkuLast"] = true,
	["electrohb"] = true,
	["drophb"] = true,
	["smitehb"] = true,
	["swimhb"] = true,
	["ravagehb"] = true,

	-- Tewi
	["c4hb"] = true,
	["carrothb"] = true,
	["carrothb2"] = true,
	["duperhb"] = true,
	["pithb"] = true,
	["proxhb"] = true,
	["chairhb"] = true,

	-- Letty
	["LettyHB"] = true,
	["LettyLast"] = true,
	["stomphb"] = true,
	["piercehb"] = true,
	["misthb"] = true,
	["winterhb"] = true,
	["winterhb2"] = true,

	-- Patchouli
	["summerredhb"] = true,
	["wipehb"] = true,
	["summerflamehb"] = true,
	["lasherhb"] = true,
	["sawbladehb"] = true,
	["autumnhb"] = true,
	["tornadohb"] = true,
	["foshb"] = true,
	["statichb"] = true,
	["prismatichb"] = true,
	
	-- itachi
	["fireballhb"] = true,
	["amahb"] = true,
	["kunaihb"] = true,
}
